name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest    
    strategy:
      matrix:
        browser: [chromium]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npx playwright install --with-deps
      - run: npm run test
      - run: npx playwright test --project=${{ matrix.browser }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-artifacts
          path: |
            playwright-report/
            test-results/
            cucumber-report/
          retention-days: 10
